In [ ]:
!pip3 install scikit-learn==0.23

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from sklearn.datasets import load_breast_cancer
from torch.utils.data import DataLoader, Dataset

In [ ]:
X, y = load_breast_cancer(return_X_y=True, as_frame=True)

In [ ]:
X2 = X.copy()
X2['y'] = y
X2.corr()
X

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]

In [ ]:
class CancerDataset(Dataset):

    def __init__(self):
        self.X, self.y = load_breast_cancer(as_frame=True, return_X_y=True)
    
    def __getitem__(self, index):
        X = self.X.iloc[index]
        y = self.y.iloc[index]
        return torch.tensor(X), torch.tensor(y)
    
    def __len__(self):
        return self.X.shape[0]

In [ ]:
ds = CancerDataset()

In [ ]:
ds[398]

(tensor([1.1060e+01, 1.4830e+01, 7.0310e+01, 3.7820e+02, 7.7410e-02, 4.7680e-02,
         2.7120e-02, 7.2460e-03, 1.5350e-01, 6.2140e-02, 1.8550e-01, 6.8810e-01,
         1.2630e+00, 1.2980e+01, 4.2590e-03, 1.4690e-02, 1.9400e-02, 4.1680e-03,
         1.1910e-02, 3.5370e-03, 1.2680e+01, 2.0350e+01, 8.0790e+01, 4.9670e+02,
         1.1200e-01, 1.8790e-01, 2.0790e-01, 5.5560e-02, 2.5900e-01, 9.1580e-02],
        dtype=torch.float64), tensor(1))

In [ ]:
class Model(nn.Module):

    def __init__(self):
        super(Model, self).__init__()
        self.layer_1 = nn.Linear(in_features=30, out_features=15)
        self.layer_2 = nn.Linear(in_features=15, out_features=1)
    
    def forward(self, x):
        x = F.relu(self.layer_1(x))
        x = F.sigmoid(self.layer_2(x))
        return x

In [ ]:
layer_1 = nn.Linear(in_features=4, out_features=2)
layer_1(torch.tensor([1., 2., 3., 4.]))

tensor([-0.0083,  2.2003], grad_fn=<AddBackward0>)

In [ ]:
def train(model, dataset):
    dataloader = DataLoader(dataset, batch_size=128)
    criterion = nn.BCELoss()
    optimizer = optim.Adam(model.parameters(), lr=7e-4)
    for epoch in range(1000):
        for b, batch in enumerate(dataloader):

            optimizer.zero_grad()

            X, y = batch
            X = X.cuda().float()
            y = y.cuda().float()

            outputs = model(X)
            loss = criterion(outputs, y)

            loss.backward()
            
            optimizer.step()
            
            print('Epoch {} Batch {} - Loss: {}'.format(epoch, b, loss))

            

In [ ]:
model = Model().cuda()
dataset = CancerDataset()
train(model, dataset)

/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1569: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:516: UserWarning: Using a target size (torch.Size([128])) that is different to the input size (torch.Size([128, 1])) is deprecated. Please ensure they have the same size.
  return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:516: UserWarning: Using a target size (torch.Size([57])) that is different to the input size (torch.Size([57, 1])) is deprecated. Please ensure they have the same size.
  return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)


Streaming output truncated to the last 5000 lines.
Epoch 0 Batch 1 - Loss: 9.305826187133789
Epoch 0 Batch 2 - Loss: 11.43830680847168
Epoch 0 Batch 3 - Loss: 11.352458000183105
Epoch 0 Batch 4 - Loss: 8.584813117980957
Epoch 1 Batch 0 - Loss: 5.427016258239746
Epoch 1 Batch 1 - Loss: 6.592329025268555
Epoch 1 Batch 2 - Loss: 8.800671577453613
Epoch 1 Batch 3 - Loss: 7.9398298263549805
Epoch 1 Batch 4 - Loss: 4.990433216094971
Epoch 2 Batch 0 - Loss: 7.243889331817627
Epoch 2 Batch 1 - Loss: 6.422492504119873
Epoch 2 Batch 2 - Loss: 8.067989349365234
Epoch 2 Batch 3 - Loss: 6.950457572937012
Epoch 2 Batch 4 - Loss: 2.186840057373047
Epoch 3 Batch 0 - Loss: 14.153236389160156
Epoch 3 Batch 1 - Loss: 12.10952091217041
Epoch 3 Batch 2 - Loss: 11.714045524597168
Epoch 3 Batch 3 - Loss: 8.437562942504883
Epoch 3 Batch 4 - Loss: 5.81189489364624
Epoch 4 Batch 0 - Loss: 28.80445671081543
Epoch 4 Batch 1 - Loss: 18.767879486083984
Epoch 4 Batch 2 - Loss: 16.510793685913086
Epoch 4 Batch 3 - Lo

In [ ]:
X, y = dataset[16]
model(X.cuda().float()), y.cuda()

/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1569: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


(tensor([0.6416], device='cuda:0', grad_fn=<SigmoidBackward>),
 tensor(0, device='cuda:0'))